
exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('candles').del()
    .then(function () {
      // Inserts seed entries
      return knex('candles').insert([
        { id: 1, name: 'Carousel Mini', size: '65g Natural Soy Wax', wick: 'Cotton Wick', price: 8, img: './images/1.jpg', details: 'These are the perfect size for small gift, party/wedding favour or a tester when your not sure which scent to choose. Bulk orders for a special occasion will have a discount applied. Email us at loveandlighthomefragrances@gmail.com to enquire.', gift_boxed: 'This Jar does not come Gift Boxed', inCart: false, count: 0, total: 0 },
        { id: 2, name: 'Carousel Large', size: '175g Natural Soy Wax', wick: 'Cotton Wick', price: 20, img: './images/2.jpg', details: 'This jar is always a favourite, very beautiful and very useful once candle has sadly finished. Wash this one out with hot soapy water and use it for your jewelery or other little nik naks.', gift_boxed: 'This Jar comes Gift Boxed', inCart: false, count: 0, total: 0 },
        { id: 3, name: 'Vintage Clear', size: '300g Natural Soy Wax', wick: 'Cotton Wick', price: 25, img: './images/1.jpg', details: 'One of our most popular sizes this jar makes a beautiful piece to add to your home or office. Wash this one out with hot soapy water and re use as the perfect lollie jar, makeup brush holder, bathroom storage.', gift_boxed: 'This Jar comes Gift Boxed', inCart: false, count: 0, total: 0 },
        { id: 4, name: 'Vintage Tiffany Blue', size: '300g Natural Soy Wax', wick: 'Cotton Wick', price: 25, img: './images/4.jpg', details: 'One of our most popular candles with its beautiful colour. This jar also comes in the clear glass. Wash this one out with hot soapy water and re use as the perfect lollie jar, makeup brush holder, bathroom storage.', gift_boxed: 'This Jar comes Gift Boxed', inCart: false, count: 0, total: 0 },
        { id: 5, name: 'Geo Large', size: '500g Natural Soy Wax', wick: 'Double Cotton Wick', price: 35, img: './images/4.jpg', details: 'This jar is our most popular size when looking for the perfect gift. The Geo is made with 2 wicks for a more even burn and the one to choose when you cant get enough of your fragrance and need it to last.', gift_boxed: 'This Jar comes Gift Boxed', inCart: false, count: 0, total: 0 },
        { id: 6, name: 'Renee Mauve Marble', size: '500g Natural Soy Wax', wick: 'Cotton Wick', price: 35, img: './images/2.jpg', details: 'This one is a personal favourite of mine and such a nice piece to add to your home. When your candle has sadly finished, wash out with hot soapy water and re use as a beautiful drinking/wine glass.', gift_boxed: 'This Jar comes Gift Boxed', inCart: false, count: 0, total: 0 },
        { id: 7, name: 'Renee Pink Marble', size: '500g Natural Soy Wax', wick: 'Cotton Wick', price: 35, img: './images/5.jpg', details: 'This one is a personal favourite of mine and such a nice piece to add to your home. When your candle has sadly finished, wash out with hot soapy water and re use as a beautiful drinking/wine glass.', gift_boxed: 'This Jar comes Gift Boxed', inCart: false, count: 0, total: 0 },
        { id: 8, name: 'Omg', size: '620g Natural Soy Wax', wick: 'Triple Cotton Wick', price: 40, img: './images/2.jpg', details: 'Our biggest one yet, this candle is made with three wicks to ensure an even burn. A beautiful statement piece to add in any home or office', gift_boxed: 'This Jar comes Gift Boxed', inCart: false, count: 0, total: 0 },
      ]);
    });
};